# -*- coding: utf-8 -*-
"""Glints.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1-3HImjHMrVBu8mm5JzrJd_Hhttxj2uUM
# Scraping Glints
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

URL = "https://glints.com/id/opportunities/jobs/explore?keyword=jakarta&country=ID&locationName=Indonesia"
page = requests.get(URL)
soup = BeautifulSoup(page.text, "html.parser")
jobs = soup.find_all('div',{'class':'ExploreTabsc__Body-sc-gs9c0s-3 fFULhl'})
data = []
for job in produk:
    title = job.select('.job card title')
    company = job.select('.job-company')
    location = job.select('.job-location')
    print(title)
    # data.append({"Title": title[0].text.strip(), "Company": company[0].text.strip(), "Location": location[0].text.strip()})

#print(data)
df = pd.DataFrame(data)
print(df)

import requests
from bs4 import BeautifulSoup
import csv
url = 'https://www.glints.com/id/jobs?page=1'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

jobs = soup.find_all('a', {'class': 'job-card'})

for job in jobs:
    title = job.find('h3', {'class': 'job-title'}).get_text()
    company = job.find('h4', {'class': 'job-company'}).get_text()
    location = job.find('span', {'class': 'job-location'}).get_text()
    print(title, company, location)